name = "talkingtrump"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# Environment variables will be set in Cloudflare Pages dashboard
# REPLICATE_API_TOKEN = "your_replicate_api_token_here"
# NEWS_API_KEY = "your_news_api_key_here"
